### ISSUE TITLE
[BUG] Missing COSESign1 Tag for messages involving COSE Signatures.

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#28]
To simplify issue resolution process, please provide network logs, and or test voucher.
[to1_msg33_cosetag_logs.txt](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12168340/to1_msg33_cosetag_logs.txt)
[to2_msg65_encrypttag_logs.txt](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12298919/to2_msg65_encrypttag_logs.txt)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [x] TO1
- [x] TO2

## Issue description

- COSESign1 Tag **'18'** is missing from message 33 sent by conformance RV server.

    **Expected Message Begin with:**
    d28444*
    **Actual/Observed Message Begin with:**
    844*

    Missing **d2 in CBOR / 18 in Diagnostic** tag from message. Observed same in message 61.

- COSEEncrypt Tag **'16'** is missing from message 65 sent by conformance owner server.

  **Expected Message Begin with:**
  d08343*
  **Actual/Observed Message Begin with:**
  8343*

   Missing **d0 in CBOR / 16 in Diagnostic** tag from message.

- This is related to [https://github.com/fido-alliance/fdo-fido-conformance-server/issues/8](url)

**Comment by herrjemand** [comment]
Closing in respect to #8
