### ISSUE TITLE
[BUG] Error generating voucher

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/fdo-fido-conformance-server#37]
To simplify issue resolution process, please provide network logs, and or test voucher.
```
2023/09/10 20:40:59 Generate vouchers. Error generating voucher f1d0fd00-8b4e-4a80-801d-8c667eb11a8d for test FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION. Error generating OVEntry. error generating ES256 cose signature. Could not cast privKey instance to ECDSA PrivateKey
2023/09/10 20:40:59 Responding error: Failed to generate vouchers. Internal server error. HTTP code 500
```

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
 - Internal server error response when calling API `api/dot/create`.
 - Type of input `prevEntryPriKey` and `prevEntrySgType` are conflict here: 
 https://github.com/fido-alliance/fdo-fido-conformance-server/blob/7e3793a69557037fe3463fba23fac34d745039df/core/device/genvoucher.go#L193

**Comment by herrjemand** [comment]
Resolved
