### ISSUE TITLE
[BUG] Exception in decryption of message 65 when using AES GCM and CCM ciphersuites

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#38]
To simplify issue resolution process, please provide network logs, and or test voucher.
[aad_bytes_conformance_owner.log](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12597075/aad_bytes_conformance_owner.log)

![aad_value_client](https://github.com/fido-alliance/fdo-fido-conformance-server/assets/68411840/57f2264c-8fe4-4b23-9422-8e32d7856be8)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description

- While decryption message 65 sent by conformance owner, client throws following exceptions for respective cipher suites and results in failure of message decryption.
    - For AES256GCM, the exception is **_javax.crypto.AEADBadTagException: Tag mismatch!_**
    - For AES_CCM_64_128_128, the exception is  _**java.io.IOException: org.bouncycastle.crypto.InvalidCipherTextException: mac check in CCM failed**_
- In both the cases, AAD bytes are used for authentication check and following are observations w.r.t the same
     - [x] At [https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/signing.misc.go#L50](url), the context must be **"Encrypt0"** rather than **"Encrypt"** as mentioned in [https://tinyurl.com/aadrfc](url)
     
     - [x] It is observed that at [https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/enc.crypto.go#L218](url) **protectedHeaderInner** returns unwanted values similar to #27 and missing map type for **"Alg"**
          - Log for conformance owner by adding print statements is attached.
     - [x] Also, it is observed, that encoded aadbytes returns invalid byte array which when compared with aad value generated on client side.
         - On Conformance owner side, aad byte array returns: [128] 
         - On client side, aad byte array has value of: [-125, 104, 69, 110, 99, 114, 121, 112, 116, 48, 68, -95, 1, 24, 32, 64]
         - Log for same can be seen in the same attached file for conformance server. For client side a screenshot is attached.
         - According to [https://tinyurl.com/aadencrfc](url), there is specific encoding rules to be followed for AAD struct.

**Comment by herrjemand** [comment]
@Sai-Anudeep47 yes you are correct

**Comment by Sai-Anudeep47** [comment]
The issue is still noticed with latest fix. Following is a observation upon debugging.

- protectedHeaderBytes should be used instead of unprotectedHeaderBytes in aadStruct at [https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/enc.crypto.go#L420](url) according to [https://tinyurl.com/aadstructrfc](url)

Upon modifying conformance code with above changes, the expected behavior is observed where AAD bytes generated by conformance owner is same as generated on client side. Even though AAD being matched, during authentication check for encrypted text, it throws afore mentioned exception, as follows

- For AES256GCM, the exception is javax.crypto.AEADBadTagException: Tag mismatch!
- For AES_CCM_64_128_128, the exception is java.io.IOException: org.bouncycastle.crypto.InvalidCipherTextException: mac check in CCM failed

**Comment by herrjemand** [comment]
🤦 Sorry for that.

Fixed now
