### ISSUE TITLE
[BUG] Error in adding voucher via UI

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#39]
To simplify issue resolution process, please provide network logs, and or test voucher.
[dev_voucher_add_err.log](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12672825/dev_voucher_add_err.log)

![device_voucher_add_ui_err](https://github.com/fido-alliance/fdo-fido-conformance-server/assets/68411840/a1a235de-d99e-4972-b75b-7a76c73f360f)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [ ] TO2

## Issue description
With latest fix [https://github.com/fido-alliance/fdo-fido-conformance-server/commit/34676284901fa38afacbf21bcabf0399e1382e17](url) ,when uploading voucher via UI, an error "**NetworkError when attempting to fetch resource**" is observed. and following error is observed in logs. The stack trace for the same error is present in log attached.

- **http: panic serving 127.0.0.1:48822: interface conversion: interface {} is fdoshared.DeviceSgType, not *int**

**Comment by Sai-Anudeep47** [comment]
Sent the voucher via email

**Comment by herrjemand** [comment]
That is now addressed

**Comment by herrjemand** [comment]
Ref #40
