### ISSUE TITLE
[BUG] Error when building code

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#42]
To simplify issue resolution process, please provide network logs, and or test voucher.
[make_build_err.log](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12709240/make_build_err.log)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [ ] TO2

## Issue description

- When building code on Linux, following error is observed

> GOOS=windows go build -o ./bin//fdo-fido-conformance-server-windows.exe
> #github.com/fido-alliance/fdo-fido-conformance-server/core/shared
> core/shared/enc.crypto.go:492:2: undefined: log
> make: *** [Makefile:28: compile_win] Error 1

- Upon commenting the above line at [ https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/enc.crypto.go#L492](url) , getting following error.

> GOOS=windows go build -o ./bin//fdo-fido-conformance-server-windows.exe
> #github.com/fido-alliance/fdo-fido-conformance-server/core/shared
> core/shared/enc.crypto.go:9:2: "encoding/hex" imported and not used
> make: *** [Makefile:28: compile_win] Error 1

- The error is resolved by commenting the above line [https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/enc.crypto.go#L9](url)

**Comment by herrjemand** [comment]
jup. addressed
