### ISSUE TITLE
[BUG] Incompatiple pkType and pkBody

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/fdo-fido-conformance-server#43]
To simplify issue resolution process, please provide network logs, and or test voucher.
[f1d0fd00b0c143378d9699c205482eb4.voucher.txt](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12711389/f1d0fd00b0c143378d9699c205482eb4.voucher.txt)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [ ] TO2

## Issue description
 - The voucher is received from API "/api/dot/vouchers/{uuid}". After parsing the voucher, received public key with `pkType` = 5, equivalent to RSA3072, but the `pkBody` is RSA2048.
 - This is related to https://github.com/fido-alliance/fdo-fido-conformance-server/issues/19
 - When generating RSA key, the value of `pkType` is fixed with RSAPKCS https://github.com/fido-alliance/fdo-fido-conformance-server/blob/bed48409e41da82fc603fa89ef645ca8cc5acb14/core/shared/voucher.go#L343

**Comment by herrjemand** [comment]
This is now addressed
