### ISSUE TITLE
[BUG] Incorrect PRF declared and used in KDF for ciphersuites A256GCM and AES-CCM-64-128-256

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#51]
To simplify issue resolution process, please provide network logs, and or test voucher.
![a256gcm_hash_hmac_value](https://github.com/fido-alliance/fdo-fido-conformance-server/assets/68411840/d0953ef2-e8e1-4cc1-bc14-650c0149d1c1)
![AES-CCM-64-128-256_hash_hmac_value](https://github.com/fido-alliance/fdo-fido-conformance-server/assets/68411840/557d85ca-b19b-493d-ab59-792b50c90862)
![kdf_hmac_spec](https://github.com/fido-alliance/fdo-fido-conformance-server/assets/68411840/282f14df-880f-475f-946e-0732a8e612d2)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description

- The PRF / HMAC used in KDF for cipher suites A256GCM and AES-CCM-64-128-256 is not accordance in spec as mentioned at https://tinyurl.com/ciphersuitesprf 
- It is observed that HMAC-SHA384 is used on conformance owner (https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/enc.crypto.go#L86) for the mentioned ciphers instead of HMAC-SHA256 as provided in spec link. 
- This is also resulting in generating incorrect keys for encryption and decryption related to #46 
- Screenshots are attached for reference.

**Comment by herrjemand** [comment]
Good catch @Sai-Anudeep47

**Comment by Sai-Anudeep47** [comment]
@herrjemand the issue is still observed. There is a miss in fixing this for encrypt/decrypt EMB functions. At https://github.com/fido-alliance/iot-fdo-conformance-tools/blob/main/core/shared/enc.crypto.go#L441 and https://github.com/fido-alliance/iot-fdo-conformance-tools/blob/main/core/shared/enc.crypto.go#L491 it is still using 

> alg.HmacAlg

 instead of 

> alg.KdfHmacAlg
